FROM registry.redhat.io/ubi9/python-311

EXPOSE 5000

WORKDIR /opt/app

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY server.py .

ENV PYTHONUNBUFFERED=1
ENV BROKER_HOST=message-broker
ENV BROKER_PORT=6379
ENV SOCKETIO_PORT=5000

CMD ["python3", "server.py"]
